import { useState, type FormEvent } from 'react'
import { Button, Callout, FormGroup, InputGroup, TextArea, Tooltip } from '@blueprintjs/core'
import type { ResearchTopic, Security, Tag, Taxonomy, Watchlist } from '../domain/types'
import { useApp } from '../app/AppContext'
import { DialogActions, DraggableDialog } from './DraggableDialog'

const COLORS = ['#4F7CAC','#2E8B78','#7A5AF8','#C47F17','#C25555','#9B5C8F','#667085','#3478C9']
function ErrorText({ error }: { error: string }) { return error ? <Callout className="form-error" intent="danger" role="alert">{error}</Callout> : null }
function ColorPicker({ value, onChange }: { value: string; onChange(value: string): void }) { return <div className="color-picker">{COLORS.map((color) => <Tooltip key={color} content={color}><Button type="button" aria-label={`Select color ${color}`} className={value === color ? 'selected':''} style={{background:color}} onClick={()=>onChange(color)} icon={value===color?'tick':undefined}/></Tooltip>)}</div> }

export function SecurityForm({ security, onClose }: { security?: Security; onClose(): void }) {
  const app = useApp(); const [symbol,setSymbol]=useState(security?.symbol ?? ''); const [alternativeId,setAlternativeId]=useState(security?.alternativeId ?? ''); const [currency,setCurrency]=useState(security?.currency ?? ''); const [name,setName]=useState(security?.name ?? ''); const [error,setError]=useState('')
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');try{if(security)await app.updateSecurity({...security,symbol,alternativeId,currency,name});else await app.addSecurity({symbol,alternativeId,currency,name});onClose()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}}
  return <DraggableDialog title={security?'Edit security':'New security'} onClose={onClose}><form onSubmit={submit} className="form-grid"><FormGroup label="Symbol" labelFor="security-symbol"><InputGroup id="security-symbol" autoFocus maxLength={20} value={symbol} onChange={(e)=>setSymbol(e.target.value)} placeholder="For example, AAPL"/></FormGroup><FormGroup label="Alternative ID" labelInfo="(optional)" labelFor="security-alternative-id"><InputGroup id="security-alternative-id" maxLength={80} value={alternativeId} onChange={(e)=>setAlternativeId(e.target.value)} placeholder="For example, US0378331005"/></FormGroup><FormGroup label="Currency" labelFor="security-currency"><InputGroup id="security-currency" maxLength={8} value={currency} onChange={(e)=>setCurrency(e.target.value)} placeholder="For example, USD"/></FormGroup><FormGroup label="Company name" labelFor="security-name"><InputGroup id="security-name" maxLength={160} value={name} onChange={(e)=>setName(e.target.value)} placeholder="For example, Apple Inc."/></FormGroup><ErrorText error={error}/><DialogActions><Button text="Cancel" onClick={onClose}/><Button type="submit" intent="primary" text="Save" disabled={!symbol.trim()||!currency.trim()||!name.trim()}/></DialogActions></form></DraggableDialog>
}

export function WatchlistForm({ watchlist, onClose }: { watchlist?:Watchlist;onClose(): void }) {
  const app=useApp();const[name,setName]=useState(watchlist?.name??'');const[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{if(watchlist)await app.updateWatchlist({...watchlist,name});else await app.addWatchlist(name);onClose()}catch(r){setError(r instanceof Error?r.message:String(r))}}
  return <DraggableDialog title={watchlist?'Rename watchlist':'New watchlist'} onClose={onClose} width={420}><form onSubmit={submit} className="form-grid"><FormGroup label="List name" labelFor="watchlist-name"><InputGroup id="watchlist-name" autoFocus maxLength={80} value={name} onChange={(e)=>setName(e.target.value)} placeholder="For example, Watchlist"/></FormGroup><ErrorText error={error}/><DialogActions><Button text="Cancel" onClick={onClose}/><Button type="submit" intent="primary" text="Save" disabled={!name.trim()}/></DialogActions></form></DraggableDialog>
}

export function TaxonomyForm({ onClose }: { onClose(): void }) {
  const app=useApp();const[name,setName]=useState('');const[description,setDescription]=useState('');const[color,setColor]=useState(COLORS[0]);const[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await app.addTaxonomy({name,description,color});onClose()}catch(r){setError(r instanceof Error?r.message:String(r))}}
  return <DraggableDialog title="New taxonomy" onClose={onClose}><form onSubmit={submit} className="form-grid"><FormGroup label="Name" labelFor="taxonomy-name"><InputGroup id="taxonomy-name" autoFocus maxLength={80} value={name} onChange={(e)=>setName(e.target.value)} placeholder="For example, Investment Thesis"/></FormGroup><FormGroup label="Description" labelInfo="(optional)" labelFor="taxonomy-description"><TextArea id="taxonomy-description" fill value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Describe the purpose of this taxonomy"/></FormGroup><FormGroup label="Color"><ColorPicker value={color} onChange={setColor}/></FormGroup><ErrorText error={error}/><DialogActions><Button text="Cancel" onClick={onClose}/><Button type="submit" intent="primary" text="Save" disabled={!name.trim()}/></DialogActions></form></DraggableDialog>
}

export function ResearchTopicForm({topic,onClose}:{topic?:ResearchTopic;onClose():void}) {
  const app=useApp();const[title,setTitle]=useState(topic?.title??'');const[error,setError]=useState('')
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');try{if(topic)await app.updateResearchTopic({id:topic.id,title});else await app.addResearchTopic(title);onClose()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}}
  return <DraggableDialog title={topic?'Edit research topic':'New research topic'} onClose={onClose} width={520}><form onSubmit={submit} className="form-grid"><FormGroup label="Topic title" labelFor="research-topic-title"><InputGroup id="research-topic-title" autoFocus maxLength={180} value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="For example, Serial acquirers in vertical-market software"/></FormGroup><ErrorText error={error}/><DialogActions><Button text="Cancel" onClick={onClose}/><Button type="submit" intent="primary" text="Save" disabled={!title.trim()}/></DialogActions></form></DraggableDialog>
}

export function TagForm({ taxonomy, parent, tag, onSaved, onClose }: { taxonomy: Taxonomy; parent?: Tag; tag?: Tag; onSaved(): void; onClose(): void }) {
  const app=useApp();const[name,setName]=useState(tag?.name??'');const[description,setDescription]=useState(tag?.description??'');const[color,setColor]=useState(tag?.color||parent?.color||taxonomy.color);const[error,setError]=useState('');
  const submit=async(e:FormEvent)=>{e.preventDefault();try{if(tag)await app.repository.updateTag({id:tag.id,taxonomyId:taxonomy.id,name,description,color});else await app.repository.addTag({taxonomyId:taxonomy.id,parentId:parent?.id??null,name,description,color});await onSaved();onClose()}catch(r){setError(r instanceof Error?r.message:String(r))}}
  return <DraggableDialog title={tag?'Edit tag':'New tag'} onClose={onClose}><form onSubmit={submit} className="form-grid">{!tag&&<Callout className="form-context" icon="diagram-tree">Parent: {parent?.name??taxonomy.name}</Callout>}<FormGroup label="Name" labelFor="tag-name"><InputGroup id="tag-name" autoFocus maxLength={80} value={name} onChange={(e)=>setName(e.target.value)} placeholder="For example, Strong pricing power"/></FormGroup><FormGroup label="Description" labelInfo="(optional)" labelFor="tag-description"><TextArea id="tag-description" fill value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Describe how this tag should be used"/></FormGroup><FormGroup label="Color"><ColorPicker value={color} onChange={setColor}/></FormGroup><ErrorText error={error}/><DialogActions><Button text="Cancel" onClick={onClose}/><Button type="submit" intent="primary" text="Save" disabled={!name.trim()}/></DialogActions></form></DraggableDialog>
}

export function ConfirmDialog({ title, message, confirmLabel='Yes', onConfirm, onClose }: { title:string;message:string;confirmLabel?:string;onConfirm():Promise<void>;onClose():void }) {
  const[error,setError]=useState('');const confirm=async()=>{try{await onConfirm();onClose()}catch(r){setError(r instanceof Error?r.message:String(r))}}
  return <DraggableDialog title={title} onClose={onClose} width={460}><Callout intent="danger" icon="warning-sign">{message}</Callout><ErrorText error={error}/><DialogActions><Button text="No" onClick={onClose}/><Button intent="danger" text={confirmLabel} onClick={confirm}/></DialogActions></DraggableDialog>
}
