import { useEffect, useMemo, useState, type MouseEvent } from 'react'
import { Button, HTMLTable, InputGroup, Menu, MenuItem, PopoverNext, showContextMenu } from '@blueprintjs/core'
import { useApp } from '../app/AppContext'
import type { ResearchTopic } from '../domain/types'
import { ConfirmDialog, ResearchTopicForm } from './Forms'
import { PageHeader, PageToolbarIconBar, PageToolbarIconButton } from './PageHeader'

type TopicRow={topic:ResearchTopic;relatedCount:number}

function displayDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(value))}

export function ResearchTopicsView() {
  const app=useApp();const[rows,setRows]=useState<TopicRow[]>([]);const[searchQuery,setSearchQuery]=useState('');const[creating,setCreating]=useState(false);const[editing,setEditing]=useState<ResearchTopic>();const[deleting,setDeleting]=useState<ResearchTopic>()
  useEffect(()=>{let active=true;Promise.all(app.researchTopics.map(async(topic)=>({topic,relatedCount:(await app.repository.getResearchTopicRelations(topic.id)).relatedSecurities.length}))).then((next)=>{if(active)setRows(next)});return()=>{active=false}},[app.repository,app.researchTopics])
  const query=searchQuery.trim().toLocaleLowerCase(),filteredRows=useMemo(()=>query?rows.filter(({topic})=>topic.title.toLocaleLowerCase().includes(query)):rows,[query,rows]),searching=Boolean(query)
  const description=searching?`${filteredRows.length} of ${rows.length} research ${rows.length===1?'topic':'topics'}`:'Develop research that spans companies, themes, sectors, and strategies.'
  const topicMenu=(topic:ResearchTopic)=><Menu><MenuItem icon="edit" text="Edit topic" onClick={()=>setEditing(topic)}/><MenuItem icon="trash" intent="danger" text="Delete topic" onClick={()=>setDeleting(topic)}/></Menu>
  const openMenu=(event:MouseEvent,topic:ResearchTopic)=>{event.preventDefault();showContextMenu({targetOffset:{left:event.clientX,top:event.clientY},isDarkTheme:document.documentElement.classList.contains('bp6-dark'),content:topicMenu(topic)})}
  return <main className="content page"><PageHeader title="Research Topics" description={description} actions={<PageToolbarIconBar label="Research topic controls"><InputGroup className="security-search" type="search" leftIcon="search" placeholder="Search research topics" aria-label="Search research topics" value={searchQuery} onChange={(event)=>setSearchQuery(event.target.value)} rightElement={searchQuery?<Button variant="minimal" icon="cross" aria-label="Clear search" onClick={()=>setSearchQuery('')}/>:undefined}/><PageToolbarIconButton icon="add" label="New topic" onClick={()=>setCreating(true)}/></PageToolbarIconBar>}/><div className="content-panel data-card"><HTMLTable className="security-table topic-table" compact interactive striped><thead><tr><th>Topic</th><th>Related securities</th><th>Last updated</th><th aria-label="Actions"/></tr></thead><tbody>{filteredRows.map(({topic,relatedCount})=><tr key={topic.id} onDoubleClick={()=>app.openResearchTopic(topic.id)} onContextMenu={(event)=>openMenu(event,topic)}><td><button className="topic-title-link" onClick={()=>app.openResearchTopic(topic.id)}>{topic.title}</button></td><td>{relatedCount}</td><td>{displayDate(topic.updatedAt)}</td><td><PopoverNext content={topicMenu(topic)} placement="bottom-end" animation="minimal" arrow={false} shouldReturnFocusOnClose={false}><Button variant="minimal" size="small" icon="more" aria-label={`Actions for ${topic.title}`}/></PopoverNext></td></tr>)}</tbody></HTMLTable>{rows.length===0?<div className="empty-state"><p>No research topics yet.</p><Button icon="add" text="Create your first topic" onClick={()=>setCreating(true)}/></div>:searching&&filteredRows.length===0?<div className="empty-state">No research topics match “{searchQuery.trim()}”.</div>:null}</div>{creating&&<ResearchTopicForm onClose={()=>setCreating(false)}/>} {editing&&<ResearchTopicForm topic={editing} onClose={()=>setEditing(undefined)}/>} {deleting&&<ConfirmDialog title="Delete research topic" message={`Delete “${deleting.title}” and all of its research notes? Securities and tags will not be deleted.`} confirmLabel="Delete" onClose={()=>setDeleting(undefined)} onConfirm={()=>app.deleteResearchTopic(deleting.id)}/>}</main>
}
