import { useState } from 'react'
import { Button, ButtonGroup, HTMLSelect, InputGroup, Menu, MenuItem, PopoverNext } from '@blueprintjs/core'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import Underline from '@tiptap/extension-underline'
import Link from '@tiptap/extension-link'
import Color from '@tiptap/extension-color'
import { TextStyle } from '@tiptap/extension-text-style'
import Highlight from '@tiptap/extension-highlight'
import { TableKit } from '@tiptap/extension-table'
import { Bold, Italic, UnderlineIcon, Strikethrough, List, ListOrdered, Outdent, Indent, Link2, Table2, Undo2, Redo2, Rows3, Columns3, Trash2 } from 'lucide-react'

const TEXT_COLORS=['#172033','#F2F4F7','#C25555','#C47F17','#2E8B78','#3478C9','#7A5AF8','#9B5C8F','#667085','#000000','#FFFFFF','#B42318']
const HIGHLIGHTS=['#FFF2A8','#F6C7C7','#FAD8B4','#C7E9D9','#C9DDF5','#DDD1FA','#E4E7EC','#FDE68A','#FECACA','#BBF7D0','#BFDBFE','#E9D5FF']

function Tool({label,active=false,disabled=false,onClick,children}:{label:string;active?:boolean;disabled?:boolean;onClick():void;children:React.ReactNode}){return <Button type="button" title={label} aria-label={label} variant="minimal" size="small" active={active} className="editor-tool" disabled={disabled} onMouseDown={(e)=>e.preventDefault()} onClick={onClick}>{children}</Button>}
function Palette({colors,clear,onSelect}:{colors:string[];clear:string;onSelect(color:string):void}){return <div className="editor-palette"><div>{colors.map((color)=><Button key={color} style={{background:color}} aria-label={color} onClick={()=>onSelect(color)}/>)}</div><Button variant="minimal" fill className="clear-color" text={clear} onClick={()=>onSelect('')}/></div>}

export function RichTextEditor({content,onChange}:{content:string;onChange(html:string):void}){
  const[colorMenu,setColorMenu]=useState<'text'|'highlight'|null>(null);const[linkOpen,setLinkOpen]=useState(false);const[href,setHref]=useState('');const[tableOpen,setTableOpen]=useState(false)
  const editor=useEditor({extensions:[StarterKit.configure({link:false,underline:false}),Underline,Link.configure({openOnClick:false,autolink:true}),TextStyle,Color,Highlight.configure({multicolor:true}),TableKit.configure({table:{resizable:true}})],content:content||'<p></p>',editorProps:{attributes:{class:'rich-editor','aria-label':'Research notes'}},onUpdate:({editor})=>onChange(editor.getHTML())})
  if(!editor)return null
  const block=editor.isActive('heading',{level:1})?'h1':editor.isActive('heading',{level:2})?'h2':'p'
  const setLink=()=>{if(!href.trim())editor.chain().focus().unsetLink().run();else editor.chain().focus().extendMarkRange('link').setLink({href}).run();setLinkOpen(false)}
  const textPalette=<Palette colors={TEXT_COLORS} clear="Automatic" onSelect={(color)=>{color?editor.chain().focus().setColor(color).run():editor.chain().focus().unsetColor().run();setColorMenu(null)}}/>
  const highlightPalette=<Palette colors={HIGHLIGHTS} clear="No highlight" onSelect={(color)=>{color?editor.chain().focus().setHighlight({color}).run():editor.chain().focus().unsetHighlight().run();setColorMenu(null)}}/>
  const linkEditor=<div className="link-popover"><InputGroup autoFocus value={href} onChange={(e)=>setHref(e.target.value)} placeholder="https://example.com" onKeyDown={(e)=>{if(e.key==='Enter')setLink()}} rightElement={<Button variant="minimal" icon="arrow-right" onClick={setLink} aria-label="Apply link"/>}/></div>
  return <div className="editor-shell"><div className="editor-toolbar">
    <ButtonGroup className="tool-group" variant="minimal"><Tool label="Undo" disabled={!editor.can().undo()} onClick={()=>editor.chain().focus().undo().run()}><Undo2/></Tool><Tool label="Redo" disabled={!editor.can().redo()} onClick={()=>editor.chain().focus().redo().run()}><Redo2/></Tool></ButtonGroup>
    <div className="tool-group"><HTMLSelect aria-label="Paragraph style" value={block} onChange={(e)=>{if(e.target.value==='p')editor.chain().focus().setParagraph().run();else editor.chain().focus().toggleHeading({level:e.target.value==='h1'?1:2}).run()}} options={[{value:'p',label:'Paragraph'},{value:'h1',label:'Heading 1'},{value:'h2',label:'Heading 2'}]} minimal/></div>
    <ButtonGroup className="tool-group" variant="minimal"><Tool label="Bold" active={editor.isActive('bold')} onClick={()=>editor.chain().focus().toggleBold().run()}><Bold/></Tool><Tool label="Italic" active={editor.isActive('italic')} onClick={()=>editor.chain().focus().toggleItalic().run()}><Italic/></Tool><Tool label="Underline" active={editor.isActive('underline')} onClick={()=>editor.chain().focus().toggleUnderline().run()}><UnderlineIcon/></Tool><Tool label="Strikethrough" active={editor.isActive('strike')} onClick={()=>editor.chain().focus().toggleStrike().run()}><Strikethrough/></Tool>
      <PopoverNext content={textPalette} isOpen={colorMenu==='text'} onInteraction={(open)=>setColorMenu(open?'text':null)} placement="bottom-start" animation="minimal" arrow={false} shouldReturnFocusOnClose={false}><Tool label="Text color" onClick={()=>setColorMenu(colorMenu==='text'?null:'text')}><span className="letter-tool">A<i/></span></Tool></PopoverNext>
      <PopoverNext content={highlightPalette} isOpen={colorMenu==='highlight'} onInteraction={(open)=>setColorMenu(open?'highlight':null)} placement="bottom-start" animation="minimal" arrow={false} shouldReturnFocusOnClose={false}><Tool label="Highlight color" active={editor.isActive('highlight')} onClick={()=>setColorMenu(colorMenu==='highlight'?null:'highlight')}><span className="highlight-tool">A</span></Tool></PopoverNext>
    </ButtonGroup>
    <ButtonGroup className="tool-group" variant="minimal"><Tool label="Bulleted list" active={editor.isActive('bulletList')} onClick={()=>editor.chain().focus().toggleBulletList().run()}><List/></Tool><Tool label="Numbered list" active={editor.isActive('orderedList')} onClick={()=>editor.chain().focus().toggleOrderedList().run()}><ListOrdered/></Tool><Tool label="Decrease indentation" onClick={()=>editor.chain().focus().liftListItem('listItem').run()}><Outdent/></Tool><Tool label="Increase indentation" onClick={()=>editor.chain().focus().sinkListItem('listItem').run()}><Indent/></Tool></ButtonGroup>
    <ButtonGroup className="tool-group" variant="minimal"><PopoverNext content={linkEditor} isOpen={linkOpen} onInteraction={setLinkOpen} placement="bottom-start" animation="minimal" arrow={false} shouldReturnFocusOnClose={false}><Tool label="Insert link" active={editor.isActive('link')} onClick={()=>{setHref(editor.getAttributes('link').href??'');setLinkOpen(!linkOpen)}}><Link2/></Tool></PopoverNext><PopoverNext content={<Menu><MenuItem icon="th" text="Insert 3 × 3 table" onClick={()=>{editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run();setTableOpen(false)}}/></Menu>} isOpen={tableOpen} onInteraction={setTableOpen} placement="bottom-start" animation="minimal" arrow={false} shouldReturnFocusOnClose={false}><Tool label="Insert table" onClick={()=>setTableOpen(!tableOpen)}><Table2/></Tool></PopoverNext></ButtonGroup>
    {editor.isActive('table')&&<ButtonGroup className="tool-group table-tools" variant="minimal"><Tool label="Add row" onClick={()=>editor.chain().focus().addRowAfter().run()}><Rows3/></Tool><Tool label="Delete row" onClick={()=>editor.chain().focus().deleteRow().run()}><Rows3/><small>−</small></Tool><Tool label="Add column" onClick={()=>editor.chain().focus().addColumnAfter().run()}><Columns3/></Tool><Tool label="Delete column" onClick={()=>editor.chain().focus().deleteColumn().run()}><Columns3/><small>−</small></Tool><Tool label="Delete table" onClick={()=>editor.chain().focus().deleteTable().run()}><Trash2/></Tool></ButtonGroup>}
  </div><EditorContent editor={editor}/></div>
}
