import { useCallback, useEffect, useMemo, useRef, useState, type DragEvent, type FormEvent } from 'react'
import { Button, Callout, FormGroup, HTMLTable, InputGroup } from '@blueprintjs/core'
import { useApp } from '../app/AppContext'
import type { SecurityDocument } from '../domain/types'
import { formatFileSize, openSecurityDocument, pickPdfSources, removeSecurityDocument, revealSecurityDocument, storeSecurityDocument, type PdfImportSource } from '../utils/securityDocumentStorage'
import { ConfirmDialog } from './Forms'
import { DialogActions, DraggableDialog } from './DraggableDialog'

function displayDate(value:string){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(`${value}T12:00:00`)):'—'}
function displayTimestamp(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(value))}

function DocumentMetadataDialog({document,onClose,onSaved}:{document:SecurityDocument;onClose():void;onSaved():void}){
  const app=useApp();const[title,setTitle]=useState(document.title);const[source,setSource]=useState(document.source);const[documentDate,setDocumentDate]=useState(document.documentDate);const[error,setError]=useState('');const[saving,setSaving]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{await app.repository.updateSecurityDocument({id:document.id,title,source,documentDate});onSaved();onClose()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setSaving(false)}}
  return <DraggableDialog title="Edit document details" width={480} onClose={onClose}><form className="form-grid" onSubmit={submit}><FormGroup label="Title" labelFor="document-title"><InputGroup id="document-title" autoFocus value={title} onChange={(event)=>setTitle(event.target.value)}/></FormGroup><FormGroup label="Source" labelInfo="(optional)" labelFor="document-source"><InputGroup id="document-source" value={source} onChange={(event)=>setSource(event.target.value)} placeholder="For example, UBS"/></FormGroup><FormGroup label="Report date" labelInfo="(optional)" labelFor="document-date"><InputGroup id="document-date" type="date" value={documentDate} onChange={(event)=>setDocumentDate(event.target.value)}/></FormGroup>{error&&<p className="form-error">{error}</p>}<DialogActions><Button text="Cancel" onClick={onClose}/><Button type="submit" intent="primary" text="Save" loading={saving} disabled={!title.trim()}/></DialogActions></form></DraggableDialog>
}

export function SecurityDocuments({securityId,onCountChange}:{securityId:string;onCountChange?(count:number):void}){
  const app=useApp();const[documents,setDocuments]=useState<SecurityDocument[]>([]);const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[importing,setImporting]=useState(false);const[dragging,setDragging]=useState(false);const[status,setStatus]=useState('');const[editing,setEditing]=useState<SecurityDocument>();const[deleting,setDeleting]=useState<SecurityDocument>();const mounted=useRef(true)
  const load=useCallback(async()=>{const next=await app.repository.listSecurityDocuments(securityId);if(!mounted.current)return;setDocuments(next);onCountChange?.(next.length);setLoading(false)},[app.repository,onCountChange,securityId])
  useEffect(()=>{mounted.current=true;setLoading(true);setQuery('');setStatus('');void load().catch((reason)=>{if(mounted.current){setStatus(reason instanceof Error?reason.message:String(reason));setLoading(false)}});return()=>{mounted.current=false}},[load])

  const importSources=useCallback(async(sources:PdfImportSource[])=>{if(!sources.length)return;setImporting(true);setStatus('');let imported=0;const failures:string[]=[];try{for(const source of sources){let stored:Awaited<ReturnType<typeof storeSecurityDocument>>|undefined;try{stored=await storeSecurityDocument(securityId,source);await app.repository.addSecurityDocument(stored);imported++}catch(reason){if(stored)await removeSecurityDocument(stored.storagePath).catch(()=>{});failures.push(reason instanceof Error?reason.message:String(reason))}}await load();if(failures.length)setStatus(`${imported?`${imported} ${imported===1?'document':'documents'} attached. `:''}${failures.join(' ')}`);else setStatus(`${imported} ${imported===1?'document':'documents'} attached.`)}catch(reason){setStatus(reason instanceof Error?reason.message:String(reason))}finally{setImporting(false)}},[app.repository,load,securityId])

  useEffect(()=>{if(!('__TAURI_INTERNALS__' in window))return;let unlisten:(()=>void)|undefined,active=true;import('@tauri-apps/api/webview').then(({getCurrentWebview})=>getCurrentWebview().onDragDropEvent((event)=>{if(!active)return;if(event.payload.type==='enter'||event.payload.type==='over')setDragging(true);else if(event.payload.type==='leave')setDragging(false);else{setDragging(false);const paths=event.payload.paths.filter((path)=>path.toLocaleLowerCase().endsWith('.pdf'));if(paths.length)void importSources(paths.map((path)=>({kind:'path',path})));else setStatus('Only PDF documents can be attached.')}})).then((stop)=>{unlisten=stop});return()=>{active=false;unlisten?.()}},[importSources])

  const choose=async()=>{try{await importSources(await pickPdfSources())}catch(reason){setStatus(reason instanceof Error?reason.message:String(reason))}}
  const dropBrowser=(event:DragEvent)=>{event.preventDefault();setDragging(false);void importSources([...event.dataTransfer.files].map((file)=>({kind:'file',file})))}
  const openDocument=async(document:SecurityDocument)=>{setStatus('');try{await openSecurityDocument(document.storagePath)}catch(reason){setStatus(reason instanceof Error?reason.message:String(reason))}}
  const revealDocument=async(document:SecurityDocument)=>{setStatus('');try{await revealSecurityDocument(document.storagePath)}catch(reason){setStatus(reason instanceof Error?reason.message:String(reason))}}
  const deleteDocument=async(document:SecurityDocument)=>{await app.repository.deleteSecurityDocument(document.id);const fileRemoved=await removeSecurityDocument(document.storagePath).then(()=>true).catch(()=>false);setDeleting(undefined);await load();if(!fileRemoved)setStatus('The document was removed, but its managed file could not be cleaned up.')}
  const filtered=useMemo(()=>{const value=query.trim().toLocaleLowerCase();return value?documents.filter((document)=>[document.title,document.source,document.originalFilename].some((field)=>field.toLocaleLowerCase().includes(value))):documents},[documents,query])
  const desktop='__TAURI_INTERNALS__' in window

  return <div className="security-documents"><div className="documents-toolbar"><InputGroup type="search" leftIcon="search" placeholder="Search documents" aria-label="Search documents" value={query} onChange={(event)=>setQuery(event.target.value)} rightElement={query?<Button variant="minimal" icon="cross" aria-label="Clear document search" onClick={()=>setQuery('')}/>:undefined}/><Button icon="paperclip" text="Add PDFs" loading={importing} onClick={()=>void choose()}/></div>{status&&<Callout className="documents-status" intent={status.includes('attached.')&&!status.includes('Only')?'success':'warning'}>{status}</Callout>}<div className={`documents-drop-zone ${dragging?'active':''}`} onDragEnter={(event)=>{event.preventDefault();setDragging(true)}} onDragOver={(event)=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={dropBrowser}>
    {loading?<div className="empty-state">Loading documents…</div>:filtered.length?<HTMLTable className="security-table document-table" compact interactive striped><thead><tr><th>Title</th><th>Source</th><th>Report date</th><th>Size</th><th>Added</th><th aria-label="Actions"/></tr></thead><tbody>{filtered.map((document)=><tr key={document.id} onDoubleClick={()=>void openDocument(document)}><td><button className="document-title-link" onClick={()=>void openDocument(document)}>{document.title}</button><small>{document.originalFilename}</small></td><td>{document.source||'—'}</td><td>{displayDate(document.documentDate)}</td><td>{formatFileSize(document.fileSize)}</td><td>{displayTimestamp(document.createdAt)}</td><td><Button variant="minimal" size="small" icon="document-open" title="Open document" aria-label={`Open ${document.title}`} onClick={()=>void openDocument(document)}/>{desktop&&<Button variant="minimal" size="small" icon="folder-open" title="Reveal in Finder or Explorer" aria-label={`Reveal ${document.title}`} onClick={()=>void revealDocument(document)}/>}<Button variant="minimal" size="small" icon="edit" title="Edit document details" aria-label={`Edit ${document.title}`} onClick={()=>setEditing(document)}/><Button variant="minimal" size="small" icon="trash" intent="danger" title="Delete document" aria-label={`Delete ${document.title}`} onClick={()=>setDeleting(document)}/></td></tr>)}</tbody></HTMLTable>:<div className="empty-state"><p>{query.trim()?'No matching documents.':'Drop PDF documents here or use Add PDFs.'}</p></div>}
  </div>{editing&&<DocumentMetadataDialog document={editing} onClose={()=>setEditing(undefined)} onSaved={()=>void load()}/>} {deleting&&<ConfirmDialog title="Delete document" message={`Delete “${deleting.title}”? The managed PDF copy will also be removed.`} confirmLabel="Delete" onClose={()=>setDeleting(undefined)} onConfirm={()=>deleteDocument(deleting)}/>}</div>
}
