import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Button, ButtonGroup, Card, Tag as BlueprintTag } from '@blueprintjs/core'
import { useApp } from '../app/AppContext'
import type { Tag, Taxonomy } from '../domain/types'
import { TagAssignmentDialog } from './TagAssignmentDialog'
import { ResearchJournal } from './ResearchJournal'

const RichTextEditor = lazy(() => import('./RichTextEditor').then((module) => ({ default: module.RichTextEditor })))

export function SecurityDetailView({id}:{id:string}){
  const app=useApp();const security=app.securities.find((x)=>x.id===id);const[tags,setTags]=useState<Tag[]>([]);const[assigned,setAssigned]=useState<string[]>([]);const[assigning,setAssigning]=useState(false);const[content,setContent]=useState('');const[status,setStatus]=useState('');const[loadedNoteId,setLoadedNoteId]=useState('');const[noteLoadError,setNoteLoadError]=useState('');const[researchTab,setResearchTab]=useState<'thesis'|'journal'>('thesis');const contentRef=useRef('');const loadedIdRef=useRef('')
  const loadAssignments=useCallback(async()=>{const groups=await Promise.all(app.taxonomies.map((x)=>app.repository.listTags(x.id)));setTags(groups.flat());setAssigned(await app.repository.assignedTagIds(id))},[app.repository,app.taxonomies,id])
  useEffect(()=>{loadAssignments()},[loadAssignments]);useEffect(()=>{let active=true;loadedIdRef.current='';setLoadedNoteId('');setNoteLoadError('');setContent('');contentRef.current='';setStatus('');app.repository.loadNote(id).then((note)=>{if(!active)return;loadedIdRef.current=id;contentRef.current=note.contentHtml;setContent(note.contentHtml);setStatus(note.updatedAt?'Saved':'');setLoadedNoteId(id)}).catch((reason)=>{if(!active)return;setNoteLoadError(reason instanceof Error?reason.message:String(reason))});return()=>{active=false}},[app.repository,id])
  useEffect(()=>{if(loadedNoteId!==id||content===contentRef.current)return;setStatus('Unsaved changes');const noteId=id,noteContent=content;const timer=setTimeout(async()=>{try{await app.repository.saveNote(noteId,noteContent);if(loadedIdRef.current!==noteId)return;contentRef.current=noteContent;setStatus('Saved')}catch(r){if(loadedIdRef.current===noteId)setStatus(r instanceof Error?r.message:String(r))}},1200);return()=>clearTimeout(timer)},[app.repository,content,id,loadedNoteId])
  const grouped=useMemo(()=>app.taxonomies.map((taxonomy)=>({taxonomy,tags:tags.filter((tag)=>tag.taxonomyId===taxonomy.id&&assigned.includes(tag.id))})).filter((x)=>x.tags.length),[app.taxonomies,tags,assigned])
  if(!security)return <main className="content page"><div className="empty-state">Security not found.</div></main>
  const remove=async(tagId:string)=>{await app.repository.setAssignedTags(id,assigned.filter((x)=>x!==tagId));await loadAssignments()}
  return <main className="content page detail-page"><header className="security-heading"><h1>{security.symbol}</h1><p>{security.name}</p></header><Card className="content-panel info-card" elevation={0}><div><span>Symbol</span><strong>{security.symbol}</strong></div><div><span>Currency</span><strong>{security.currency}</strong></div><div><span>Company name</span><strong>{security.name}</strong></div></Card>
    <Card className="content-panel classification-card" elevation={0}><header><h2>Classification</h2><Button icon="add" text="Add tags" size="small" onClick={()=>setAssigning(true)}/></header>{grouped.length===0?<p className="muted">No tags assigned yet</p>:grouped.map(({taxonomy,tags})=><div className="assigned-group" key={taxonomy.id}><h3>{taxonomy.name}</h3><div>{tags.map((tag)=><BlueprintTag interactive round minimal onRemove={()=>remove(tag.id)} style={{borderColor:tag.color}} key={tag.id}>{tag.name}</BlueprintTag>)}</div></div>)}</Card>
    <Card className="content-panel notes-card" elevation={0}><header><h2>Research Notes</h2><ButtonGroup className="research-tabs" role="tablist"><Button role="tab" aria-selected={researchTab==='thesis'} active={researchTab==='thesis'} text="Current Thesis" onClick={()=>setResearchTab('thesis')}/><Button role="tab" aria-selected={researchTab==='journal'} active={researchTab==='journal'} text="Journal" onClick={()=>setResearchTab('journal')}/></ButtonGroup>{researchTab==='thesis'&&<><span>{status}</span><Button icon="floppy-disk" text="Save" size="small" disabled={loadedNoteId!==id} onClick={async()=>{const noteId=id,noteContent=content;try{await app.repository.saveNote(noteId,noteContent);if(loadedIdRef.current!==noteId)return;contentRef.current=noteContent;setStatus('Saved')}catch(reason){if(loadedIdRef.current===noteId)setStatus(reason instanceof Error?reason.message:String(reason))}}}/></>}</header>{researchTab==='thesis'?(noteLoadError?<div className="empty-state">Could not load current thesis: {noteLoadError}</div>:loadedNoteId!==id?<div className="empty-state">Loading editor…</div>:<Suspense fallback={<div className="empty-state">Loading editor…</div>}><RichTextEditor key={id} content={content} onChange={setContent}/></Suspense>):<ResearchJournal key={id} securityId={id}/>}</Card>
    {assigning&&<TagAssignmentDialog securityId={id} onClose={()=>setAssigning(false)} onSaved={loadAssignments}/>}
  </main>
}
