import { useCallback, useEffect, useRef, useState, type MouseEvent, type PointerEvent } from 'react'
import { Callout, Menu, MenuItem, Tree, type TreeNodeInfo, showContextMenu } from '@blueprintjs/core'
import { useApp } from '../app/AppContext'
import { buildTagTree, type Security, type Tag, type TaggedSecurity, type TagNode } from '../domain/types'
import { ConfirmDialog, TagForm } from './Forms'

type TaxonomyTreeData = { kind:'tag';tag:Tag }|{ kind:'security';security:Security;tagId:string }
const copyModifierPressed=(event:{altKey:boolean;ctrlKey:boolean})=>/Mac|iPhone|iPad|iPod/.test(navigator.platform)?event.altKey:event.ctrlKey

export function TaxonomyView({ id }: { id:string }) {
  const app=useApp();const taxonomy=app.taxonomies.find((x)=>x.id===id);const[tags,setTags]=useState<Tag[]>([]);const[taggedSecurities,setTaggedSecurities]=useState<TaggedSecurity[]>([]);const[expanded,setExpanded]=useState<Set<string>>(new Set(['root']));const[form,setForm]=useState<{parent?:Tag;tag?:Tag}|null>(null);const[deleting,setDeleting]=useState<Tag>();const[dropTarget,setDropTarget]=useState('');const[copying,setCopying]=useState(false);const[moveError,setMoveError]=useState('')
  const draggedSecurity=useRef<{securityId:string;tagId:string}|null>(null)
  const hoveredTag=useRef('')
  const copyingRef=useRef(false)
  const updateCopyFeedback=(copy:boolean)=>{copyingRef.current=copy;setCopying(copy);document.documentElement.classList.toggle('taxonomy-security-copying',copy)}
  const load=useCallback(async()=>{const[nextTags,nextSecurities]=await Promise.all([app.listTags(id),app.repository.listTaggedSecurities(id)]);setTags(nextTags);setTaggedSecurities(nextSecurities)},[app,id]);useEffect(()=>{load()},[load]);
  useEffect(()=>{const updateCopyMode=(event:KeyboardEvent)=>{if(draggedSecurity.current)updateCopyFeedback(copyModifierPressed(event))};document.addEventListener('keydown',updateCopyMode);document.addEventListener('keyup',updateCopyMode);return()=>{document.removeEventListener('keydown',updateCopyMode);document.removeEventListener('keyup',updateCopyMode);document.documentElement.classList.remove('taxonomy-security-dragging','taxonomy-security-copying')}},[])
  if(!taxonomy)return <main className="content page"><div className="empty-state">Taxonomy not found.</div></main>
  const toggle=(value:string)=>setExpanded((current)=>{const next=new Set(current);if(next.has(value))next.delete(value);else next.add(value);return next})
  const tree=buildTagTree(tags)
  const openMenu=(event:MouseEvent,tag?:Tag)=>{event.preventDefault();showContextMenu({targetOffset:{left:event.clientX,top:event.clientY},isDarkTheme:document.documentElement.classList.contains('bp6-dark'),content:<Menu><MenuItem icon="add" text="Add Tag" onClick={()=>{setForm({parent:tag});if(tag)setExpanded((x)=>new Set(x).add(tag.id))}}/><MenuItem icon="edit" text="Edit Tag" disabled={!tag} onClick={()=>setForm({tag})}/><MenuItem icon="trash" intent="danger" text="Delete Tag" disabled={!tag} onClick={()=>setDeleting(tag)}/></Menu>})}
  const openSecurityMenu=(event:MouseEvent,securityId:string,tagId:string)=>{event.preventDefault();showContextMenu({targetOffset:{left:event.clientX,top:event.clientY},isDarkTheme:document.documentElement.classList.contains('bp6-dark'),content:<Menu><MenuItem icon="remove" text="Remove from this tag" onClick={async()=>{setMoveError('');try{await app.repository.removeSecurityTag(securityId,tagId);await load()}catch(reason){setMoveError(reason instanceof Error?reason.message:String(reason))}}}/></Menu>})}
  const placeDraggedSecurity=async(toTagId:string,copy:boolean)=>{const payload=draggedSecurity.current;draggedSecurity.current=null;hoveredTag.current='';document.documentElement.classList.remove('taxonomy-security-dragging');updateCopyFeedback(false);setDropTarget('');setMoveError('');if(!payload||payload.tagId===toTagId)return;try{if(copy)await app.repository.copySecurityTag(payload.securityId,toTagId);else await app.repository.moveSecurityTag(payload.securityId,payload.tagId,toTagId);setExpanded((current)=>new Set(current).add(toTagId));await load()}catch(reason){setMoveError(reason instanceof Error?reason.message:String(reason))}}
  const tagAtPoint=(x:number,y:number)=>{const point=document.elementFromPoint?.(x,y);const label=point?.closest<HTMLElement>('[data-taxonomy-tag-id]')??point?.closest('.bp6-tree-node-content')?.querySelector<HTMLElement>('[data-taxonomy-tag-id]');return label?.dataset.taxonomyTagId??''}
  const startPointerDrag=(event:PointerEvent<HTMLElement>)=>{if(event.button&&event.button!==0)return;const row=(event.target as Element).closest('.bp6-tree-node-content');const label=row?.querySelector<HTMLElement>('.taxonomy-security-label[data-security-id][data-tag-id]');const securityId=label?.dataset.securityId,tagId=label?.dataset.tagId;if(!securityId||!tagId)return;draggedSecurity.current={securityId,tagId};hoveredTag.current='';updateCopyFeedback(copyModifierPressed(event));document.documentElement.classList.add('taxonomy-security-dragging');event.currentTarget.setPointerCapture?.(event.pointerId)}
  const movePointerDrag=(event:PointerEvent<HTMLElement>)=>{if(!draggedSecurity.current)return;event.preventDefault();const tagId=tagAtPoint(event.clientX,event.clientY);hoveredTag.current=tagId;setDropTarget(tagId);if(event.altKey||event.ctrlKey)updateCopyFeedback(copyModifierPressed(event))}
  const finishPointerDrag=(event:PointerEvent<HTMLElement>)=>{if(!draggedSecurity.current)return;const tagId=tagAtPoint(event.clientX,event.clientY)||hoveredTag.current;event.currentTarget.releasePointerCapture?.(event.pointerId);if(tagId)void placeDraggedSecurity(tagId,copyModifierPressed(event)||copyingRef.current);else cancelPointerDrag()}
  const cancelPointerDrag=()=>{draggedSecurity.current=null;hoveredTag.current='';document.documentElement.classList.remove('taxonomy-security-dragging');updateCopyFeedback(false);setDropTarget('')}
  const convert=(node:TagNode):TreeNodeInfo<TaxonomyTreeData>=>{const childNodes:TreeNodeInfo<TaxonomyTreeData>[]=[...node.children.map(convert),...taggedSecurities.filter((item)=>item.tagId===node.id).map((security)=>({id:`security:${node.id}:${security.id}`,nodeData:{kind:'security' as const,security,tagId:node.id},label:<span className="taxonomy-security-label" data-security-id={security.id} data-tag-id={node.id} title="Drag to move; hold the copy modifier to copy">{security.symbol} — {security.name}</span>,secondaryLabel:security.currency,icon:'briefcase' as const}))];return{id:node.id,nodeData:{kind:'tag',tag:node},label:<span data-taxonomy-tag-id={node.id} className={`taxonomy-node-label ${dropTarget===node.id?'drop-target':''} ${copying?'copy-target':''}`}><i style={{background:node.color}}/>{node.name}</span>,isExpanded:expanded.has(node.id),hasCaret:childNodes.length>0,childNodes}}
  const contents:TreeNodeInfo<TaxonomyTreeData|undefined>[]=[{id:'root',nodeData:undefined,label:<span className="taxonomy-node-label"><i style={{background:taxonomy.color}}/>{taxonomy.name}</span>,icon:'diagram-tree',isExpanded:expanded.has('root'),hasCaret:true,isSelected:true,childNodes:tree.map(convert)}]
  return <main className="content page"><header className="page-header"><div><h1>{taxonomy.name}</h1><p>{taxonomy.description||'Build a hierarchical classification for your research.'}</p></div></header>
    <div className="content-panel taxonomy-card" onPointerDown={startPointerDrag} onPointerMove={movePointerDrag} onPointerUp={finishPointerDrag} onPointerCancel={cancelPointerDrag}><Tree compact contents={contents} onNodeExpand={(node)=>toggle(String(node.id))} onNodeCollapse={(node)=>toggle(String(node.id))} onNodeDoubleClick={(node)=>{if(node.nodeData?.kind==='security')app.openSecurity(node.nodeData.security.id)}} onNodeContextMenu={(node,_path,event)=>{if(!node.nodeData)openMenu(event);else if(node.nodeData.kind==='tag')openMenu(event,node.nodeData.tag);else openSecurityMenu(event,node.nodeData.security.id,node.nodeData.tagId)}}/></div>{moveError&&<Callout className="taxonomy-move-error" intent="danger">Could not update security assignment: {moveError}</Callout>}
    {form&&<TagForm taxonomy={taxonomy} parent={form.parent} tag={form.tag} onSaved={load} onClose={()=>setForm(null)}/>} {deleting&&<ConfirmDialog title="Delete tag" message={`Do you really want to delete ${deleting.name}?`} onClose={()=>setDeleting(undefined)} onConfirm={async()=>{await app.repository.deleteTag(id,deleting.id);await load()}}/>}
  </main>
}
